services:
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio_data:/data"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: examplebucket
      MINIO_DOMAIN: "localhost:9000"
      MINIO_SCHEME: http
      MINIO_SERVER_URL: "http://localhost:9000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/target/
    environment:
      S3_ENDPOINT: "http://localhost:9000"
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: user
      AWS_SECRET_ACCESS_KEY: password
      S3_BUCKET_NAME: examplebucket
      S3_FORCE_PATH_STYLE: "true"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      LINK_SHORTENER_ENDPOINT: "https://links.viets.dev/links"
      LINK_SHORTENER_RANDOM_SLUG: "true"
    ports:
      - 3000:3000

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app
      - /app/node_modules/
    ports:
      - 5173:5173
